# This workflow will build a .NET project

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  Configuration: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Log in to container registry
      uses: azure/docker-login@v2
      with:
        login-server: crnet7containersaustraliaeast.azurecr.io
        username: crnet7containersaustraliaeast
        password: ${{ secrets.ACR_PAT }}

    - name: Publish
      run: dotnet publish --os linux --arch x64 -p:PublishProfile=azure